### ISSUE TITLE
How do I go about to testing changes?

### ISSUE THREAD

**Issue by yusufnazir** [syampillai/SOCharts#18]
Hi Syam, I recently did a checkout of the project. I am quite impressed with the gantt chart and wanted to see if I could make a few changes. My first obstacle is how you test changes within the project. How should i proceed?

**Comment by syampillai** [comment]
Currently, there is no test environment within the project.
Since it is a Vaadin addon, you may have to manipulate the POM to create a test environment or do a separate test project that uses the jar file from this project.
If you create a better POM for doing this, please let me know so that I can merge your changes.
